export const GLOSSARY: Record<string, string> = {
  "base rate":    "Tỷ lệ class dương (positive) trong tập dữ liệu. Nếu = 50%, hai class cân bằng. Lệch nhiều giữa Train/Val/Test → có distribution shift.",
  "auc":          "Area Under ROC Curve. Đo khả năng phân biệt class. 0.5 = random, > 0.6 = có tín hiệu, > 0.7 = tốt cho financial data.",
  "pr-auc":       "Precision-Recall AUC. Phù hợp khi class imbalanced. Nhạy với positive class hơn ROC-AUC.",
  "f1":           "Trung bình điều hòa của Precision và Recall. Đo cân bằng giữa false positives và false negatives.",
  "leakage":      "Rò rỉ dữ liệu — khi feature hoặc pipeline 'nhìn thấy' thông tin tương lai. Triệu chứng: train/test AUC > 0.95 bất thường. PHẢI = Không cho mọi module.",
  "ablation":     "Thí nghiệm bỏ từng feature/module để đo đóng góp. Δ AUC âm = bỏ feature đó làm giảm performance (feature quan trọng).",
  "stack":        "Stacking ensemble. Tầng base (LGBM, RF, LSTM, TCN) sinh out-of-fold predictions, tầng meta học từ chúng. Purge + embargo trên CV để tránh leakage time-series.",
  "hurdle":       "Hurdle model hai tầng: Stage 1 phân loại có move hay flat, Stage 2 dự báo độ lớn return chỉ trên non-flat samples. Tốt hơn single regression khi return phân phối lệch.",
  "sharpe":       "Sharpe Ratio = mean(return) / std(return). > 1 = tốt, > 2 = xuất sắc. Đo lợi nhuận đã điều chỉnh rủi ro.",
  "mdd":          "Maximum Drawdown — sụt giảm lớn nhất từ peak đến đáy trên equity curve. -10% = chấp nhận được, < -20% = rủi ro cao.",
  "win rate":     "Tỷ lệ trade thắng (return > 0). > 50% là dấu hiệu tốt nhưng phải kết hợp với payoff ratio.",
  "walk-forward": "Backtest cuốn chiếu — train trên past, test trên next window, lặp lại. Mô phỏng deployment thực tế, tránh look-ahead bias.",
  "smote":        "Synthetic Minority Over-sampling Technique. Sinh thêm sample class thiểu số bằng nội suy. CHỈ áp dụng trên train, không val/test.",
  "purge":        "Loại bỏ sample gần biên fold trong CV để label không overlap với train, ngăn leakage time-series.",
  "embargo":      "Khoảng cách giữa train và val fold để tránh autocorrelation.",
  "oof":          "Out-of-fold predictions — predictions trên fold giữ lại trong K-fold CV. Dùng làm input cho meta-learner trong stacking.",
  "binary":       "Phân loại nhị phân — return up (1) vs down (0). Pipeline chính.",
  "multiclass":   "Phân loại 3 class — down / flat / up. Pipeline phụ, dùng cho hurdle.",
  "llm calendar": "LLM-extracted farming calendar. Claude API đọc báo cáo USDA/CONAB và trả về JSON có cấu trúc: planting%, crop conditions, production forecast. Thay thế binary is_planting/is_harvest bằng continuous features.",
  "synthetic calendar": "Calendar tổng hợp dùng rule cứng theo tháng: is_planting = month.isin([4,5]). Đơn giản nhưng không phản ánh biến động năm theo năm.",
  "hybrid calendar": "Kết hợp synthetic calendar (A) + LLM features (B). Mục tiêu bổ trợ: LLM thêm signals granular, synthetic giữ lại cyclical patterns.",
  "psd": "USDA Production Supply Distribution — database báo cáo sản lượng hàng năm theo commodity và quốc gia. Dùng làm fallback khi CONAB PDFs không accessible.",
};
